spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  liquibase:
    change-log: ${LIQUIBASE_CHANGELOG}
    enabled: ${LIQUIBASE_ENABLED}

server:
  port: ${PORT}

